### ISSUE TITLE
Gradient used in MGS.

### ISSUE THREAD

**Issue by IpadLi** [vicFigure/ZARTS#1]
Hi,

Thanks very much for the work. I am trying to understand the code and make the connection to the paper (I apologize if I make mistakes in understanding and please correct me).

From the paper, one basic assumption is that the optimization does not require the gradient of validation loss w.r.t alpha because it is assumed to be non-differentiable. In "train_search.py", it seems we still need access to the gradient:

`base_loss, grads = architect.obtain_loss_grad(input_search, target_search, unrolled=args.unrolled)`

I am not an expert in this area, so maybe this question is not always correct. I would appreciate it if you could give me some comments on this part.

**Comment by vicFigure** [comment]
Hi,

MGS adopts the importance sampling technique to sample the update of alpha ($\Delta \alpha$), and the sampling distribution obeys a Gaussian distribution whose expectation is the first-order approximate gradient w.r.t. alpha. We can also directly sample from a standard Gaussian/uniform distribution, but the performance will degrade since it can degrade to random search.

In this paper, we would like to show that the first/second-order approximation for the gradient w.r.t. alpha in DARTS is not accurate, which can lead to a biased optimum. Nevertheless, the first/second-order approximation can be used as an effective prior of the sampling distribution.  To some degree (less-rigorous), we can regard the importance sampling process in MGS as a rectification of the gradient.

I hope the answer will resolve your concerns.

**Comment by IpadLi** [comment]
Hi vicFigure,

Thank you very much for your quick response. So, if I cannot get the gradient, does it mean that I cannot use this method? Or I can only use Gaussian/uniform distribution as you mentioned? That is, the objective function (i.e. the validation loss in the paper) is totally a black-box function.

**Comment by vicFigure** [comment]
Hi IpadLi,

The approximated gradient can be used (e.g. in the paper, we use the first-order approximation). I think that the approximated gradient is one of the most important reasons making MGS much more effective than RS and GLD.

In the cases that you cannot even get the approximated gradient, you should increase the number of samples during the importance sampling process in MGS, which, however, will increase the search time.

**Comment by IpadLi** [comment]
Thanks. So that means, in my case, the proposal distribution $q(u|\alpha)$ may be the uniform distribution, and I need to increase the number of samples $N$ in Eq. (8). But as you said, without access to the approximated gradient, MGS may not work well. And increasing the number of samples will increase the search time. Is my understanding correct?

By the way, can we say the RS and GLD are very similar in terms of sampling strategies?

**Comment by vicFigure** [comment]
Yes, your understanding is correct.

As far as I am concerned, RS and GLD have different sampling strategies. In RS, samples obey some spherically symmetric distribution, i.e., RS only samples the direction of the update with fixed magnitude ($\mu$ in our paper). While in GLD, samples obey several spherically symmetric distributions with various radii, i.e., GLD samples both the direction and the magnitude.

**Comment by IpadLi** [comment]
Great. Thank you.
